[2023-12-27T15:51:00.798+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: consumer_dag.consume_task scheduled__2023-12-27T15:50:00+00:00 [queued]>
[2023-12-27T15:51:00.803+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: consumer_dag.consume_task scheduled__2023-12-27T15:50:00+00:00 [queued]>
[2023-12-27T15:51:00.804+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-12-27T15:51:00.814+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): consume_task> on 2023-12-27 15:50:00+00:00
[2023-12-27T15:51:00.817+0000] {standard_task_runner.py:57} INFO - Started process 211 to run task
[2023-12-27T15:51:00.819+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'consumer_dag', 'consume_task', 'scheduled__2023-12-27T15:50:00+00:00', '--job-id', '349', '--raw', '--subdir', 'DAGS_FOLDER/consumer.py', '--cfg-path', '/tmp/tmpfk2p18tj']
[2023-12-27T15:51:00.819+0000] {standard_task_runner.py:85} INFO - Job 349: Subtask consume_task
[2023-12-27T15:51:00.848+0000] {task_command.py:410} INFO - Running <TaskInstance: consumer_dag.consume_task scheduled__2023-12-27T15:50:00+00:00 [running]> on host c56b1de7f6cf
[2023-12-27T15:51:00.903+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='consumer_dag' AIRFLOW_CTX_TASK_ID='consume_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-27T15:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-27T15:50:00+00:00'
[2023-12-27T15:51:20.905+0000] {logging_mixin.py:150} INFO - 메시지 없음
[2023-12-27T15:51:20.910+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-12-27T15:51:20.919+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=consumer_dag, task_id=consume_task, execution_date=20231227T155000, start_date=20231227T155100, end_date=20231227T155120
[2023-12-27T15:51:20.942+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-12-27T15:51:20.964+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
