[2023-12-27T16:46:07.544+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: consumer_dag.consume_task scheduled__2023-12-27T16:44:00+00:00 [queued]>
[2023-12-27T16:46:07.551+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: consumer_dag.consume_task scheduled__2023-12-27T16:44:00+00:00 [queued]>
[2023-12-27T16:46:07.552+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-12-27T16:46:07.562+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): consume_task> on 2023-12-27 16:44:00+00:00
[2023-12-27T16:46:07.566+0000] {standard_task_runner.py:57} INFO - Started process 3628 to run task
[2023-12-27T16:46:07.568+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'consumer_dag', 'consume_task', 'scheduled__2023-12-27T16:44:00+00:00', '--job-id', '414', '--raw', '--subdir', 'DAGS_FOLDER/consumer.py', '--cfg-path', '/tmp/tmp6dvkxf2p']
[2023-12-27T16:46:07.569+0000] {standard_task_runner.py:85} INFO - Job 414: Subtask consume_task
[2023-12-27T16:46:07.605+0000] {task_command.py:410} INFO - Running <TaskInstance: consumer_dag.consume_task scheduled__2023-12-27T16:44:00+00:00 [running]> on host c56b1de7f6cf
[2023-12-27T16:46:07.666+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='consumer_dag' AIRFLOW_CTX_TASK_ID='consume_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-27T16:44:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-27T16:44:00+00:00'
[2023-12-27T16:46:27.669+0000] {logging_mixin.py:150} INFO - 메시지 없음
[2023-12-27T16:46:27.674+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-12-27T16:46:27.683+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=consumer_dag, task_id=consume_task, execution_date=20231227T164400, start_date=20231227T164607, end_date=20231227T164627
[2023-12-27T16:46:27.710+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-12-27T16:46:27.726+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
